//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by demo1.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_DEMO1TYPE                   129
#define IDD_DLG_MOVE                    130
#define IDD_DIALOG_ZOOM                 131
#define IDD_DIALOG_Rotate               132
#define IDD_DIALOG_Histogram            133
#define IDB_BITMAP1                     134
#define IDD_DLG_THRESH                  135
#define IDD_DIALOG1                     136
#define IDD_Dlg_THRESHWD                136
#define IDD_DLG_LinearStretch           137
#define IDD_DLG_NeiborSmooth            138
#define IDD_DLG_MediaSmooth             139
#define IDD_DLG_MedianSmooth            139
#define IDD_DIALOG_HistSegment          140
#define IDC_CURSOR1                     141
#define IDC_Edit_OffsetX                1000
#define IDC_Edit_Xmove                  1000
#define IDC_Edit_OffsetY                1001
#define IDC_Edit_Ymove                  1001
#define IDC_EDIT_strechH                1002
#define IDC_EDIT_strechW                1003
#define IDC_STATIC_Rotate               1004
#define IDC_EDIT_Rotate                 1005
#define IDC_STATIC_Hist                 1006
#define IDC_STATIC_Dev                  1007
#define IDC_STATIC_Ave2                 1009
#define IDC_STATIC_AveShow              1011
#define IDC_STATIC_DevShow              1012
#define IDC_STATIC_GrayColor            1013
#define IDC_EDIT_Thresh                 1014
#define IDC_EDIT2                       1016
#define IDC_EDIT_StrechBottom           1016
#define IDC_EDIT_StrechTop              1018
#define IDC_STATIC_strechBottom         1019
#define IDC_STATIC_strechTop            1020
#define IDC_EDIT_LinetransX1            1021
#define IDC_EDIT_LinetransY1            1022
#define IDC_EDIT_LinetransX2            1023
#define IDC_EDIT_LinetransY2            1024
#define IDC_LINTRANS_SHOW               1025
#define IDC_RADIO1_temp                 1031
#define IDC_RADIO2_temp                 1032
#define IDC_RADIO3_temp                 1033
#define IDC_RADIO4_temp                 1037
#define IDC_SLIDER_GrayValue            1038
#define IDC_STATIC_Value                1039
#define IDC_STATIC_text                 1040
#define id_Move                         32771
#define id_HorizontalMirror             32772
#define id_VerticalMirror               32773
#define id_Zoom                         32774
#define id_Clockwise90                  32776
#define id_Anticlockwise90              32777
#define id_Rotate180                    32778
#define id_FreeRotate                   32779
#define id_ColorToGray                  32780
#define id_Binary                       32781
#define id_HistogramDraw                32782
#define id_ImgReverse                   32783
#define id_ImageReverse                 32783
#define id_ImgThresh                    32784
#define id_ThresholdWindow              32785
#define id_LinearStrecth                32786
#define id_DuiShuStretch                32787
#define id_ZhiShuStretch                32788
#define id_HistgramAver                 32789
#define id_GaussNoise                   32790
#define id_PepperSaltNoise              32791
#define id_AveSmooth                    32792
#define id_NeiAveSmooth                 32792
#define id_PowerSmooth                  32793
#define id_MiddleSmooth                 32794
#define id_MedianSmooth                 32794
#define id_ChooseMaskSmooth             32795
#define id_LaplacienSharp               32797
#define id_LaplaceSharp                 32797
#define ID_MENUITEM32800                32800
#define id_GradeSharp                   32801
#define id_QuickFFt                     32803
#define id_QuickFFt_Reverse             32804
#define id_IdealLowPass                 32805
#define id_ButterLowPass                32806
#define id_IdealHighPass                32807
#define id_ButterHighPass               32808
#define id_HarrWaveletTrans             32809
#define id_HarrWavRevTrans              32810
#define id_Erosion                      32811
#define id_Dilation                     32812
#define id_Open                         32813
#define id_Close                        32814
#define id_HitMissThinning              32815
#define id_Thinning                     32815
#define id_HistThreshSeg                32816
#define id_AdaptiveThreshold            32817
#define id_Robert                       32818
#define id_Sobel                        32819
#define id_Prewitt                      32820
#define id_Laplacian                    32821
#define id_RegionGrow                   32822
#define id_EdgeTrace                    32823
#define id_similardegree                32824
#define id_boundary                     32825
#define id_facelocate                   32826
#define id_innerboundary                32827
#define id_eyelocate                    32828
#define id_noselocate                   32829
#define id_mouthlocate                  32830
#define id_Wrinkle                      32831
#define id_Pot                          32832
#define id_zw                           32833
#define id_leftfacelocate               32834
#define id_rightfacelocate              32835
#define id_Adaptivethresegment          32838
#define id_GaryImage                    32842
#define id_Homomorphicfilter            32846

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         32847
#define _APS_NEXT_CONTROL_VALUE         1041
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
